export const GET_RANDOM_IMAGE_START = 'GET_RANDOM_IMAGE_START';
export const GET_RANDOM_IMAGE_END = 'GET_RANDOM_IMAGE_END';
export const GET_RANDOM_IMAGE_SUCCESS = 'GET_RANDOM_IMAGE_SUCCESS';
export const GET_RANDOM_IMAGE_FAIL = 'GET_RANDOM_IMAGE_FAIL';

export const ADD_FAVOURITE_IMAGE = 'ADD_FAVOURITE_IMAGE';

export const DELETE_FAVOURITE_IMAGE = 'DELETE_FAVOURITE_IMAGE';

export const GET_FAVOURITE_IMAGES = 'GET_FAVOURITE_IMAGES';

export const SET_ALERT = 'SET_ALERT';